import type { Metadata } from "next";
import Image from "next/image";
import { FaArrowLeftLong, FaArrowRightLong } from "react-icons/fa6";
import Logo from "../assets/logo.png";
import "./globals.css";

export const metadata: Metadata = {
  title: "Postulate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` font-inter text-white bg-black min-h-screen flex flex-col`}
      >
        <header className="flex items-center justify-between px-10 h-16 bg-[#181818] border-b-2 border-grey">
          <div className="flex items-center space-x-20">
            <div className="flex items-end">
              {/* Logo */}
              <Image src={Logo} alt="Logo" width={30} height={30} />
              <span className="ml-1 text-sm font-bold">Let's do it</span>
            </div>
            <nav className="flex space-x-8">
              <a
                href="#"
                className="text-thm h-16 flex items-center border-b-2 border-thm text-sm "
              >
                My Brand
              </a>
              <a
                href="#"
                className="text-grey-100  text-sm h-16 flex items-center "
              >
                Posts Composer
              </a>
            </nav>
          </div>
        </header>

        <main className="flex-grow">{children}</main>
        <footer className="w-full h-20 border-t-2 border-grey bg-[#181818] font-light text-sm flex items-center">
          <div className="flex gap-4 justify-end mr-48 w-full">
            <button className="bg-grey flex items-center gap-2 hover:bg-grey/90 text-white border-grey rounded-md px-4 py-2 transition-all hover:scale-95 duration-100 ease-in">
              <FaArrowLeftLong /> Previous
            </button>
            <button className="flex items-center gap-2 bg-gradient-to-r from-purple to-pink hover:bg-gradient-to-tr transition-all hover:scale-95 duration-100 ease-in text-white rounded-md px-4 py-2">
              Continue <FaArrowRightLong />
            </button>
          </div>
        </footer>
      </body>
    </html>
  );
}
