import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/Header";

export const metadata: Metadata = {
  title: "Postulate",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` font-inter text-white bg-black h-screen overflow-hidden relative flex flex-col`}
      >
        <Header />
        <main className="flex-grow ">{children}</main>
      </body>
    </html>
  );
}
